---

dnsmasq_expand_hosts: true
dnsmasq_domains:
  - domain: ranta.local
    name: ranta.local

dnsmasq_servers:
  - domain: local
    nameserver: "192.168.88.7"

dnsmasq_addresses:
  - domain: lukylab.duckdns.org
    address: "192.168.88.7"
  - domain: cloud.ranta.ch
    address: "192.168.88.7"
  - domain: ansible.ranta.local
    address: "192.168.88.7"
  - domain: home.ranta.local
    address: "192.168.88.7"
  - domain: home.ranta.ch
    address: "192.168.88.7"

  - domain: lab.ranta.local
    address: "192.168.88.5"
  - domain: vm.ansible.ranta.local
    address: "192.168.88.6"
  - domain: proxy.ranta.local
    address: "192.168.88.7"
  - domain: vm.sound.ranta.local
    address: "192.168.88.8"
  - domain: vm.home.ranta.local
    address: "192.168.88.9"
  - domain: vm.cloud.ranta.ch
    address: "192.168.88.10"
  - domain: kali.ranta.local
    address: "192.168.88.11"
  - domain: nas.ranta.local
    address: "192.168.88.250"
  - domain: k1.ranta.local
    address: "192.168.88.251"
  - domain: zigbee.ranta.local
    address: "192.168.88.254"

